[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
entity = { path = "../entity" }
migration = { path = "../migration" }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls"] }
sea-orm-migration = { workspace = true }
axum = { version = "0.8", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml = "0.0.12"
chrono = { workspace = true }
anyhow = "1"
thiserror = "2"
strum = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rust-embed = "8"
mime_guess = "2"
tower-http = { version = "0.7.0", features = ["compression-gzip"] }
parking_lot = "0.12.5"
ts-rs = { workspace = true }
subtle = "2"
csv = "1.4.0"
calamine = "0.36.1"
encoding_rs = "0.8.35"
rust_xlsxwriter = "0.97.0"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
